import {StyleSheet} from 'react-native';

export const FontStyles = StyleSheet.create({
  displayXlarge: {
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 74,
    lineHeight: 74,
    letterSpacing: -4,
    includeFontPadding: false,
  },
  displayLarge: {
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 70,
    lineHeight: 70,
    letterSpacing: 0,
    includeFontPadding: false,
  },
  displayMedium: {
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 54,
    lineHeight: 54,
    letterSpacing: -4,
    includeFontPadding: false,
  },
  displaySmall: {
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 44,
    lineHeight: 44,
    letterSpacing: -4,
    includeFontPadding: false,
  },
  HeadingXlarge: {
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 36,
    lineHeight: 36,
    letterSpacing: -4,
    includeFontPadding: false,
  },
  HeadingLarge: {
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 30,
    lineHeight: 30,
    letterSpacing: -4,
    includeFontPadding: false,
  },
  HeadingMedium: {
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 26,
    lineHeight: 26,
    letterSpacing: -4,
    includeFontPadding: false,
  },
  HeadingSmall: {
    fontFamily: 'Pretendard-SemiBold',
    fontSize: 24,
    lineHeight: 24,
    letterSpacing: -4,
    includeFontPadding: false,
  },
  BodyMedium: {
    fontFamily: 'Pretendard-Regular',
    fontSize: 24,
    lineHeight: 24,
    letterSpacing: -2,
    includeFontPadding: false,
  },
  BodySmall: {
    fontFamily: 'Pretendard-Regular',
    fontSize: 20,
    lineHeight: 20,
    letterSpacing: -2,
    includeFontPadding: false,
  },
  CaptionMedium: {
    fontFamily: 'Pretendard-Regular',
    fontSize: 16,
    lineHeight: 16,
    letterSpacing: 0,
    includeFontPadding: false,
  },
  CaptionSmall: {
    fontFamily: 'Pretendard-Regular',
    fontSize: 12,
    lineHeight: 12,
    letterSpacing: 0,
    includeFontPadding: false,
  },
});
